service: serverless-webpack-example

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x

functions:
  timezones:
    handler: src/timeZones.handler
    events:
      - http:
          path: timezones
          method: post
